### ISSUE TITLE
HTML5: missing DOCTYPE

### ISSUE THREAD

**Issue by fehmud** [madnificent/SEXML#5]
Hello,

the output of <:HTML does not return a string that starts with "<!DOCTYPE html>" when using the HTML5 DTD as shown in the README.

Thanks for your attention.

**Comment by madnificent** [comment]
I'm not sure what went wrong there.  However, the following should make it work anyway:

```
(<:augment-tag-with-doctype <:html)
(<:augment-with-doctype '<:html "")
```

After running this

```
(<:html "woop")
```

should yield 

```
"<!DOCTYPE html > <html >woop</html>"
```

Note that there is an extra space, but that shouldn't bother the browser's parser.  You can also set the doctype manually by overriding `<:*doctype*`.  You must still call `#'<:augment-tag-with-doctype` on the `<:html` symbol if you want to go that route though.

**Comment by fehmud** [comment]
Your first snippet:

   (<:augment-tag-with-doctype <:html)
   (<:augment-with-doctype '<:html "")

fixed the issue. The extra space bothers neither the browser nor the W3C validation service.

Thanks for your prompt support.

**Comment by madnificent** [comment]
I'm reopening this as it has not been fixed structurally.  Either the documentation needs to be updated, or a bugfix is in order.

**Comment by madnificent** [comment]
Updated the defaults `(<:augment-with-doctype "html" "")` works again.
