### ISSUE TITLE
How to parse the org literate file?

### ISSUE THREAD

**Issue by EuAndreh** [madnificent/SEXML#6]
What program did you use to parse the org-mode file and generate the sources and the documentation?

**Comment by madnificent** [comment]
Check out http://orgmode.org/org.html#Working-With-Source-Code in the org-mode documentation.  It's called tangling.  `C-c C-v t` is the default keybinding for tangling an org-mode file.

Generating the documentation would occur through `C-c C-e h h` for an HTML document. See http://orgmode.org/org.html#Publishing for more info on this.

**Comment by EuAndreh** [comment]
Thank you very much!
